
os: Visual Studio 2017

environment:
  matrix:
    - ARCH:                x86
      BRANCH:              master

cache:
  - bin\lld-link.exe -> windows\build_lld.bat

artifacts:
  - path: bin\lld-link.exe
    name: lld

init:
  - git config --global core.autocrlf input

build_script:
  - cd c:/projects/installer
  - if exist bin\lld-link.exe call windows\build_lld.bat

test_script: true
