os: Visual Studio 2017

environment:
  matrix:
    - ARCH:                x86
      LLVM_VER:            5.0.1

artifacts:
  - path: lld-link-$(LLVM_VER).zip
    name: lld

init:
  - git config --global core.autocrlf input

build_script:
  - call windows\build_lld.bat

test_script: true
