
os: Visual Studio 2017

environment:
  matrix:
    - ARCH:                x86
      BRANCH:              master

cache:
  - c:\projects\bin\lld-link.exe

artifacts:
  - path: c:\projects\bin\lld-link.exe
    name: lld

init:
  - git config --global core.autocrlf input

build_script:
  - cd c:/projects/
  - if exist bin\lld-link.exe goto lld_done
  - call "c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - git clone --depth 1 --branch %BRANCH% https://github.com/llvm-mirror/llvm.git llvm
  - git clone --depth 1 --branch %BRANCH% https://github.com/llvm-mirror/lld.git llvm\tools\lld
  - set PLATFORM=Win32
  - set lld_build_dir=build-lld
  - if not exist %lld_build_dir%\nul md %lld_build_dir%
  - cd %lld_build_dir%
  - set BATCH_DIR=%~dp0
  - set CMAKE_OPT=-G "Visual Studio 15"
  - set CMAKE_OPT=%CMAKE_OPT% -DCMAKE_BUILD_TYPE=Release
  - set CMAKE_OPT=%CMAKE_OPT%
  - set CMAKE_OPT=%CMAKE_OPT% -DLLVM_TARGETS_TO_BUILD=X86 
  - set CMAKE_OPT=%CMAKE_OPT% -DLLVM_INCLUDE_DIRS="c:/projects/llvm/include"
  - cmake %CMAKE_OPT% ..\llvm
  - devenv LLVM.sln /project lld /Build "MinSizeRel|Win32"
  - if not exist ..\bin\nul md ..\bin
  - copy MinSizeRel\bin\lld-link.exe ..\bin
  - cd ..
  - :lld_done

test_script: true
